aws_region            = "us-east-1"            # <<< YOUR AWS REGION
vpc_id                = "vpc-03bd3715b93b4bb68"         # <<< YOUR EXISTING VPC ID
db_identifier         = "dev-postgres-db"
db_name               = "mydb"
db_username           = "postgres"
db_password           = "admin123"  # <<< USE A STRONG PASSWORD
db_instance_class     = "db.t3.micro"
allocated_storage     = 20
engine_version        = "17.2"
